AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  leggilo-serverless

  Serverless backend for archeun leggilo
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  LeggiloFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: leggilo/
      Handler: app.leggiloHandler
      Runtime: nodejs10.x
      Events:
        Leggilo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /fetch
            Method: get
      Environment:
        Variables:
          LEGGILO_ALLOWED_ORIGINS: http://localhost:3001,https://www.archeun.com

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LeggiloApi:
    Description: "API Gateway endpoint URL for Prod stage for Leggilo function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/api/1.0/"
  LeggiloFunction:
    Description: "Leggilo Lambda Function ARN"
    Value: !GetAtt LeggiloFunction.Arn
  LeggiloFunctionIamRole:
    Description: "Implicit IAM Role created for Leggilo function"
    Value: !GetAtt LeggiloFunctionRole.Arn
